#!/bin/bash
# =============================================================
# EdithPress — Obtener certificado wildcard con Certbot
# Requiere: certbot instalado en el servidor, acceso al DNS
#
# Este script necesita ejecutarse UNA VEZ en el servidor de staging.
# Los certificados se renuevan automáticamente con el cron de Certbot.
# =============================================================
set -euo pipefail

DOMAIN="edithpress.com"
EMAIL="${CERTBOT_EMAIL:-admin@edithpress.com}"  # Cambiar por tu email real

echo "============================================"
echo "  Certbot — Wildcard SSL para $DOMAIN"
echo "============================================"
echo ""
echo "PASOS MANUALES REQUERIDOS:"
echo ""
echo "1. Instalar Certbot en el servidor:"
echo "   sudo apt update && sudo apt install -y certbot"
echo ""
echo "2. Obtener certificado wildcard (requiere DNS challenge):"
echo "   sudo certbot certonly \\"
echo "     --manual \\"
echo "     --preferred-challenges=dns \\"
echo "     --email $EMAIL \\"
echo "     --agree-tos \\"
echo "     -d $DOMAIN \\"
echo "     -d '*.$DOMAIN'"
echo ""
echo "3. Certbot te pedirá agregar un registro TXT en tu DNS:"
echo "   Tipo:  TXT"
echo "   Nombre: _acme-challenge.$DOMAIN"
echo "   Valor: (Certbot te lo dará en pantalla)"
echo ""
echo "   Esperar ~2 minutos para que el DNS propague, luego presionar Enter."
echo ""
echo "4. Verificar que los certificados se crearon:"
echo "   sudo ls /etc/letsencrypt/live/$DOMAIN/"
echo "   → Debe mostrar: cert.pem  chain.pem  fullchain.pem  privkey.pem"
echo ""
echo "5. Actualizar el docker-compose.prod.yml para montar los certs:"
echo "   En el servicio nginx, volumes:"
echo "   - /etc/letsencrypt:/etc/letsencrypt:ro"
echo "   - /var/www/certbot:/var/www/certbot:ro"
echo ""
echo "6. Configurar renovación automática (crontab):"
echo "   sudo crontab -e"
echo "   Agregar:"
echo "   0 3 * * * certbot renew --quiet && docker compose -f /opt/edithpress/docker-compose.prod.yml restart nginx"
echo ""
echo "============================================"
echo "  ALTERNATIVA: Certificado por dominio (sin wildcard)"
echo "============================================"
echo ""
echo "Si NO tienes acceso a la API del DNS para automatizar el wildcard,"
echo "puedes obtener certs por dominio individual (HTTP challenge):"
echo ""
echo "   sudo certbot certonly --webroot \\"
echo "     --webroot-path=/var/www/certbot \\"
echo "     --email $EMAIL \\"
echo "     --agree-tos \\"
echo "     -d admin.$DOMAIN \\"
echo "     -d api.$DOMAIN \\"
echo "     -d builder.$DOMAIN"
echo ""
echo "NOTA: El HTTP challenge requiere que el servidor esté accesible"
echo "      en el puerto 80 con la ruta /.well-known/acme-challenge/"
echo "      (ya configurada en nginx.staging.conf)"
echo ""
